name: PriceGuardian
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/IranSans-Black.ttf
        - asset: assets/fonts/IranSans-Bold.ttf
        - asset: assets/fonts/IranSans-DemiBold.ttf
        - asset: assets/fonts/IranSans-ExtraBold.ttf
        - asset: assets/fonts/IranSans-Light.ttf
        - asset: assets/fonts/IranSans-Medium.ttf
        - asset: assets/fonts/IranSans-Regular.ttf
        - asset: assets/fonts/IranSans-Thin.ttf
        - asset: assets/fonts/IranSans-UltraLight.ttf